FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/

RUN pip install -r requirements.txt

WORKDIR /main

ENV PATH="/main/.venv/bin:$PATH"

COPY pyproject.toml .python-version uv.lock ./
RUN uv sync --locked

COPY main.py .

ENTRYPOINT ["python", "main.py"]


