FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /main

ENV PATH="/main/.venv/bin:$PATH"

COPY main.py .

ENV PORT=8080

ENTRYPOINT ["python", "main.py"]


